import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Copy, 
  RotateCcw, 
  ThumbsUp, 
  ThumbsDown, 
  Clock, 
  ChevronDown,
  Save,
  Edit,
  Download,
  Share
} from 'lucide-react'

type Mode = 'ideate' | 'flow'
type OutputFormat = 'english' | 'json' | 'markdown'

interface ChatMessage {
  id: string
  mode: Mode
  timestamp: string
  input: string
  output: string
  title: string
  effectType?: string
  metadata?: {
    tokensUsed?: number
    creditCost?: number
    modelVersion?: string
    processingTime?: number
  }
}

interface OutputCardProps {
  message: ChatMessage
  onCopy: (text: string, format: OutputFormat) => void
  onRerun: (messageId: string) => void
  onFeedback: (messageId: string, type: 'up' | 'down') => void
  onSave?: (messageId: string) => void
  onEdit?: (messageId: string) => void
  className?: string
}

export function OutputCard({
  message,
  onCopy,
  onRerun,
  onFeedback,
  onSave,
  onEdit,
  className = ''
}: OutputCardProps) {
  const [showFormatOptions, setShowFormatOptions] = useState(false)
  const [currentFormat, setCurrentFormat] = useState<OutputFormat>('english')
  const [isExpanded, setIsExpanded] = useState(true)
  const [copySuccess, setCopySuccess] = useState<string | null>(null)

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const getModeConfig = (mode: Mode) => {
    return mode === 'ideate'
      ? { emoji: '🪄', label: 'Ideate', color: 'from-purple-400 to-pink-500' }
      : { emoji: '🌊', label: 'Flow', color: 'from-blue-400 to-cyan-500' }
  }

  const handleCopy = async (format: OutputFormat) => {
    try {
      let copyText = message.output
      
      if (format === 'json') {
        copyText = JSON.stringify({
          mode: message.mode,
          input: message.input,
          output: message.output,
          timestamp: message.timestamp,
          effectType: message.effectType,
          metadata: message.metadata
        }, null, 2)
      } else if (format === 'markdown') {
        copyText = `# Enhanced Output\n\n${message.output}\n\n---\n*Generated by PromptBrain*`
      }

      await navigator.clipboard.writeText(copyText)
      onCopy(copyText, format)
      
      setCopySuccess(`Copied as ${format.toUpperCase()}!`)
      setTimeout(() => setCopySuccess(null), 2000)
    } catch (error) {
      console.error('Copy failed:', error)
    }
  }

  const modeInfo = getModeConfig(message.mode)

  return (
    <motion.div
      initial={{ opacity: 0, y: 30, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -30, scale: 0.95 }}
      transition={{ duration: 0.5, ease: [0.2, 0.9, 0.2, 1] }}
      className={`w-full max-w-4xl mx-auto ${className}`}
    >
      {/* Main Output Card */}
      <motion.div
        whileHover={{
          boxShadow: '0 25px 50px rgba(0,0,0,0.3)',
          borderColor: 'rgba(255,255,255,0.2)'
        }}
        transition={{ duration: 0.3 }}
        className="glass-panel rounded-2xl border border-glass-border shadow-2xl overflow-hidden relative"
      >
        {/* Subtle inner glow */}
        <div className="absolute inset-0 bg-gradient-to-br from-white/5 via-transparent to-transparent rounded-2xl" />

        {/* Header Row */}
        <div className="relative z-10 flex items-center justify-between px-6 py-4 border-b border-glass-border/50">
          <div className="flex items-center space-x-3">
            {/* Mode Tag */}
            <motion.div
              className={`px-3 py-1 rounded-full text-xs font-semibold bg-gradient-to-r ${modeInfo.color} text-white shadow-lg`}
              whileHover={{ scale: 1.05 }}
            >
              {modeInfo.emoji} {modeInfo.label}
            </motion.div>

            {/* Timestamp */}
            <div className="flex items-center space-x-1 text-text-muted text-xs">
              <Clock className="w-3 h-3" />
              <span>{formatTimestamp(message.timestamp)}</span>
            </div>

            {/* Metadata */}
            {message.metadata && (
              <div className="flex items-center space-x-3 text-xs text-text-muted">
                {message.metadata.tokensUsed && (
                  <span>{message.metadata.tokensUsed} tokens</span>
                )}
                {message.metadata.creditCost && (
                  <span>{message.metadata.creditCost} credit</span>
                )}
              </div>
            )}
          </div>

          {/* Header Actions */}
          <div className="flex items-center space-x-2">
            {/* Expand/Collapse */}
            <motion.button
              onClick={() => setIsExpanded(!isExpanded)}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              className="p-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all"
              title={isExpanded ? 'Collapse' : 'Expand'}
            >
              <motion.div
                animate={{ rotate: isExpanded ? 180 : 0 }}
                transition={{ duration: 0.2 }}
              >
                <ChevronDown className="w-4 h-4" />
              </motion.div>
            </motion.button>

            {/* Re-run Button */}
            <motion.button
              onClick={() => onRerun(message.id)}
              whileHover={{ scale: 1.1, rotate: 180 }}
              whileTap={{ scale: 0.9 }}
              className="p-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all"
              title="Re-run enhancement"
            >
              <RotateCcw className="w-4 h-4" />
            </motion.button>
          </div>
        </div>

        {/* Main Output Container */}
        <AnimatePresence>
          {isExpanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: [0.2, 0.9, 0.2, 1] }}
              className="relative z-10 overflow-hidden"
            >
              <div className="p-6">
                <AnimatePresence mode="wait">
                  {currentFormat === 'english' ? (
                    <motion.div
                      key="english"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="text-text-primary leading-relaxed whitespace-pre-wrap text-base"
                    >
                      {message.output}
                    </motion.div>
                  ) : currentFormat === 'json' ? (
                    <motion.div
                      key="json"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="bg-premium-bg rounded-xl p-4 border border-green-500/20"
                    >
                      <pre className="text-green-300 text-sm font-mono overflow-x-auto">
                        {JSON.stringify({
                          mode: message.mode,
                          input: message.input,
                          output: message.output,
                          timestamp: message.timestamp,
                          effectType: message.effectType,
                          metadata: message.metadata
                        }, null, 2)}
                      </pre>
                    </motion.div>
                  ) : (
                    <motion.div
                      key="markdown"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="bg-premium-bg rounded-xl p-4 border border-blue-500/20"
                    >
                      <pre className="text-blue-300 text-sm font-mono overflow-x-auto">
                        {`# Enhanced Output\n\n${message.output}\n\n---\n*Generated by PromptBrain*`}
                      </pre>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Action Bar */}
        <div className="relative z-10 flex items-center justify-between px-6 py-4 border-t border-glass-border/50 bg-black/20">
          <div className="flex items-center space-x-3">
            {/* Copy Button with Success Animation */}
            <div className="relative">
              <motion.button
                onClick={() => handleCopy(currentFormat)}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="flex items-center space-x-2 px-3 py-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all premium-focus"
              >
                <Copy className="w-4 h-4" />
                <span className="text-sm font-medium">Copy</span>
              </motion.button>

              {/* Copy Success Indicator */}
              <AnimatePresence>
                {copySuccess && (
                  <motion.div
                    initial={{ opacity: 0, y: -10, scale: 0.8 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: -10, scale: 0.8 }}
                    className="absolute -top-10 left-1/2 -translate-x-1/2 bg-green-500 text-white px-3 py-1 rounded-lg text-xs font-medium whitespace-nowrap"
                  >
                    {copySuccess} ✓
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Format Dropdown */}
            <div className="relative">
              <motion.button
                onClick={() => setShowFormatOptions(!showFormatOptions)}
                whileHover={{ scale: 1.05 }}
                className="flex items-center space-x-2 px-3 py-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all premium-focus"
              >
                <span className="text-sm font-medium">
                  {currentFormat === 'english' ? 'English' : currentFormat === 'json' ? 'JSON' : 'Markdown'}
                </span>
                <ChevronDown className="w-3 h-3" />
              </motion.button>

              {/* Format Options Dropdown */}
              <AnimatePresence>
                {showFormatOptions && (
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.9 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.9 }}
                    className="absolute bottom-full left-0 mb-2 glass-panel-strong rounded-xl border border-glass-border py-2 shadow-2xl z-30 min-w-[160px]"
                  >
                    {[
                      { key: 'english', label: 'English', desc: 'Human readable' },
                      { key: 'json', label: 'JSON', desc: 'Structured data' },
                      { key: 'markdown', label: 'Markdown', desc: 'Formatted text' }
                    ].map((format) => (
                      <motion.button
                        key={format.key}
                        onClick={() => {
                          setCurrentFormat(format.key as OutputFormat)
                          setShowFormatOptions(false)
                        }}
                        whileHover={{ x: 4 }}
                        className="w-full text-left px-4 py-2 text-text-primary hover:bg-glass transition-all flex items-center justify-between group"
                      >
                        <div>
                          <div className="font-medium text-sm">{format.label}</div>
                          <div className="text-xs text-text-muted">{format.desc}</div>
                        </div>
                        {currentFormat === format.key && (
                          <div className="w-2 h-2 bg-brand-gold rounded-full" />
                        )}
                      </motion.button>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Additional Actions */}
            {onSave && (
              <motion.button
                onClick={() => onSave(message.id)}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="flex items-center space-x-2 px-3 py-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all premium-focus"
              >
                <Save className="w-4 h-4" />
                <span className="text-sm font-medium">Save</span>
              </motion.button>
            )}

            {onEdit && (
              <motion.button
                onClick={() => onEdit(message.id)}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="flex items-center space-x-2 px-3 py-2 text-text-muted hover:text-text-primary rounded-lg hover:bg-glass transition-all premium-focus"
              >
                <Edit className="w-4 h-4" />
                <span className="text-sm font-medium">Edit</span>
              </motion.button>
            )}
          </div>

          {/* Feedback Buttons */}
          <div className="flex items-center space-x-2">
            <motion.button
              onClick={() => onFeedback(message.id, 'up')}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              className="p-2 text-text-muted hover:text-green-400 rounded-lg hover:bg-green-500/10 transition-all premium-focus"
              title="Good result"
            >
              <ThumbsUp className="w-4 h-4" />
            </motion.button>

            <motion.button
              onClick={() => onFeedback(message.id, 'down')}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              className="p-2 text-text-muted hover:text-red-400 rounded-lg hover:bg-red-500/10 transition-all premium-focus"
              title="Poor result"
            >
              <ThumbsDown className="w-4 h-4" />
            </motion.button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}